CREATE TABLE IF NOT EXISTS Directors (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);
ALTER TABLE Films DROP COLUMN director;
ALTER TABLE Films ADD COLUMN directorId INT;

ALTER TABLE Films
    ADD CONSTRAINT fk_films_director
    FOREIGN KEY (directorId) REFERENCES Directors(id);
