ALTER TABLE Likes DROP CONSTRAINT IF EXISTS fk_likes_film;
ALTER TABLE Likes DROP CONSTRAINT IF EXISTS fk_likes_user;
ALTER TABLE Film_Genre DROP CONSTRAINT IF EXISTS fk_film_genre_film;
ALTER TABLE Friendship DROP CONSTRAINT IF EXISTS fk_friendship_user;
ALTER TABLE Friendship DROP CONSTRAINT IF EXISTS fk_friendship_friend;
ALTER TABLE Films DROP CONSTRAINT IF EXISTS fk_films_director;
ALTER TABLE Films DROP CONSTRAINT IF EXISTS fk_films_rating;

ALTER TABLE Likes ADD CONSTRAINT fk_likes_film FOREIGN KEY (filmId) REFERENCES Films(id) ON DELETE CASCADE;
ALTER TABLE Likes ADD CONSTRAINT fk_likes_user FOREIGN KEY (userId) REFERENCES Users(id) ON DELETE CASCADE;
ALTER TABLE Film_Genre ADD CONSTRAINT fk_film_genre_film FOREIGN KEY (filmId) REFERENCES Films(id) ON DELETE CASCADE;
ALTER TABLE Friendship ADD CONSTRAINT fk_friendship_user FOREIGN KEY (userId) REFERENCES Users(id) ON DELETE CASCADE;
ALTER TABLE Friendship ADD CONSTRAINT fk_friendship_friend FOREIGN KEY (friendId) REFERENCES Users(id) ON DELETE CASCADE;
ALTER TABLE Films ADD CONSTRAINT fk_films_director FOREIGN KEY (directorId) REFERENCES Directors(id) ON DELETE SET NULL;
ALTER TABLE Films ADD CONSTRAINT fk_films_rating FOREIGN KEY (ratingId) REFERENCES Rating(id) ON DELETE SET NULL;